CREATE TABLE IF NOT EXISTS WEB_NOTE (
  ID          VARCHAR(64)   NOT NULL PRIMARY KEY COMMENT 'ID',
  NOTEBOOK_ID      VARCHAR(64)   NULL COMMENT '文章所属标签ID',

  CREATE_TIME DATETIME      NOT NULL COMMENT '文章创建时间',
  MODIFY_TIME DATETIME      NULL COMMENT '文章修改时间',
  USER_ID     VARCHAR(255)  NOT NULL COMMENT '作者',
  TITLE       VARCHAR(255)  NOT NULL COMMENT '文章标题',
  ABSTRACT    TEXT          COMMENT '文章简介',
  CONTENT     TEXT          COMMENT '文章正文',
  IS_PUBLISH  BOOLEAN       NOT NULL DEFAULT 0  COMMENT '文章发布状态'
)COMMENT = '文章表';

CREATE TABLE IF NOT EXISTS WEB_NOTEBOOK (
  ID          VARCHAR(64)   NOT NULL PRIMARY KEY COMMENT 'ID',
  NAME        VARCHAR(128)  NOT NULL DEFAULT 'new tag' COMMENT '标签名',
  CREATE_TIME DATETIME      NOT NULL COMMENT '创建时间',
  MODIFY_TIME DATETIME      NOT NULL COMMENT '修改时间'
)COMMENT = '标签表';

CREATE TABLE IF NOT EXISTS WEB_USER (
  ID          VARCHAR(64)   NOT NULL PRIMARY KEY COMMENT 'ID',
  USERNAME    VARCHAR(32)   NOT NULL UNIQUE COMMENT '用户名',
  PASSWORD    VARCHAR(32)   NOT NULL COMMENT '密码',
  MOBILE      VARCHAR(32)   NOT NULL UNIQUE COMMENT '手机号码',
  HEAD_IMG    VARCHAR(255)  COMMENT '头像',
  NICKNAME    VARCHAR(64)   COMMENT '别名',
  IS_LOCK     BOOLEAN       NOT NULL DEFAULT FALSE  COMMENT '是否锁定',
  CREATE_TIME DATETIME      NOT NULL COMMENT '创建时间',
  MODIFY_TIME DATETIME      NOT NULL COMMENT '修改时间'
)COMMENT = '用户表';

DROP TABLE IF EXISTS WEB_HISTORY_NOTE;
CREATE TABLE IF NOT EXISTS WEB_HISTORY_NOTE (
  ID          VARCHAR(64)   NOT NULL PRIMARY KEY COMMENT 'ID',
  NOTE_ID  VARCHAR(64)   NULL     COMMENT '文章ID',
  CREATE_TIME DATETIME      NOT NULL COMMENT '创建时间',
  TITLE       VARCHAR(255)  NOT NULL COMMENT '标题',
  ABSTRACT    TEXT          COMMENT '文章简介',
  CONTENT     TEXT          COMMENT '正文'
)COMMENT = '文章历史记录表';
